from pathlib import Path
import os,sys,shutil,subprocess
os.environ['CUDA_VISIBLE_DEVICES']='0'
os.environ['TOKENIZERS_PARALLELISM']='false'
source=Path('/kaggle/input/notebooks/trinashih/3beethoven-v0-2')
assert (source/'seed_replication_backup_receipt.json').is_file()
assert (source/'3beethoven_seed_replication/v19_seed_31415/replication_complete.json').is_file()
repo=Path('/kaggle/working/seed_repo')
shutil.copytree(source/'seed_repo',repo,dirs_exist_ok=True,ignore=shutil.ignore_patterns('__pycache__','.git'))
(repo/"scripts/harmonize_seed_mc.py").write_text('"""Same inference loading for v15 seed MC; preserve original runner outputs."""\nimport os,json,gc,shutil,hashlib,sys\nfrom pathlib import Path\nINPUT=Path(\'/kaggle/input/notebooks/trinashih/3beethoven-v0-2\')\nROOT=Path(\'/kaggle/working/seed_mc_harmonized\')\ndef main():\n import torch\n from transformers import AutoTokenizer,AutoModelForCausalLM,BitsAndBytesConfig,set_seed\n from peft import PeftModel\n from kaggle_secrets import UserSecretsClient\n from flight_run_stats_v0_3 import STUDENT,save_json as save\n from run_stats_v0_4 import BASE_REVISION,evaluate\n from stats_v0_3_common import parse_answer\n source=INPUT/\'3beethoven_seed_replication\';ROOT.mkdir(exist_ok=True)\n all_results=json.loads((source/\'all_results.json\').read_text())\n receipt=INPUT/\'seed_replication_backup_receipt.json\'\n assert receipt.is_file(), \'Training backup receipt is required\'\n shutil.copy2(receipt,ROOT/receipt.name)\n anchor=json.loads((INPUT/\'seed_repo/docs/STATS_PERMANENT_ANCHOR_V1.json\').read_text())\n expected={(r[\'id\'],r[\'shift\']):r[\'expected\'] for r in anchor[\'mc\'][\'rotations\']}\n token=UserSecretsClient().get_secret(\'HF_TOKEN\');summary={}\n for seed in (1919,2027,31415):\n  run=f\'v15_seed_{seed}\';path=source/run/\'adapter\'\n  h=hashlib.sha256((path/\'adapter_model.safetensors\').read_bytes()).hexdigest()\n  assert h==all_results[run+\'/replication_complete.json\'][\'adapter_sha256\']\n  set_seed(seed);tok=AutoTokenizer.from_pretrained(path)\n  model=AutoModelForCausalLM.from_pretrained(STUDENT,revision=BASE_REVISION,token=token,device_map={\'\':0},torch_dtype=torch.float16,quantization_config=BitsAndBytesConfig(load_in_4bit=True,bnb_4bit_quant_type=\'nf4\',bnb_4bit_compute_dtype=torch.float16,bnb_4bit_use_double_quant=True))\n  model=PeftModel.from_pretrained(model,path)\n  summary[run]=evaluate(model,tok,anchor[\'mc\'][\'questions\'],ROOT/f\'{run}_mc.json\')\n  rows=json.loads((ROOT/f\'{run}_mc.json\').read_text());assert len(rows)==240\n  assert len({(r[\'id\'],r[\'shift\']) for r in rows})==240\n  for r in rows:assert r[\'expected\']==expected[(r[\'id\'],r[\'shift\'])] and r[\'correct\']==(parse_answer(r[\'raw\'])==r[\'expected\'])\n  all_results[run+\'/anchor_mc_original_runner.json\']=all_results[run+\'/anchor_mc.json\']\n  all_results[run+\'/anchor_mc.json\']=rows\n  print(\'HARMONIZED MC\',run,json.dumps(summary[run]),flush=True)\n  del model;gc.collect();torch.cuda.empty_cache()\n save(ROOT/\'summary.json\',summary)\n save(ROOT/\'all_results.json\',all_results)\n save(ROOT/\'provenance.json\',dict(training_updates=0,teacher_calls=0,reason=\'Use direct PeftModel inference consistently; original v15 runner prepares kbit model during its own MC evaluation\',original_training_output_preserved=True))\n print(\'HARMONIZED MC COMPLETE\',flush=True)\nif __name__==\'__main__\':main()\n')
subprocess.run([sys.executable,'-m','pip','install','-q','transformers==5.0.0','peft==0.19.1','bitsandbytes==0.50.2','datasets==5.0.0','accelerate==1.13.0'],check=True)
subprocess.run([sys.executable,str(repo/'scripts/harmonize_seed_mc.py')],cwd=repo,check=True)
